using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using System;
using System.Collections.Generic;

namespace RankApp.Migrations
{
    public partial class initial : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "MetodRobs",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    EkspertDyplom = table.Column<double>(nullable: true),
                    EkspertDyplomNRobit = table.Column<double>(nullable: true),
                    PIB = table.Column<string>(nullable: true),
                    PerekladStat = table.Column<double>(nullable: true),
                    PerekladStatNStor = table.Column<double>(nullable: true),
                    PerevirkaOlimp = table.Column<double>(nullable: true),
                    PerevirkaOlimpNRobit = table.Column<double>(nullable: true),
                    PidgotovkaDopovidTaVistup = table.Column<double>(nullable: true),
                    PidgotovkaDopovidTaVistupNVistup = table.Column<double>(nullable: true),
                    PidgotovkaLabPrakt = table.Column<double>(nullable: true),
                    PidgotovkaLekciiBakalavr = table.Column<double>(nullable: true),
                    PidgotovkaLekciiBakalavrN = table.Column<double>(nullable: true),
                    PidgotovkaLekciiMagistr = table.Column<double>(nullable: true),
                    PidgotovkaLekciiMagistrN = table.Column<double>(nullable: true),
                    PidgotovkaMater = table.Column<double>(nullable: true),
                    PidgotovkaRecenzVidkr = table.Column<double>(nullable: true),
                    PidgotovkaRecenzVidkrNZanat = table.Column<double>(nullable: true),
                    PidvKval = table.Column<double>(nullable: true),
                    RecenzPidruch = table.Column<double>(nullable: true),
                    RecenzPidruchNStor = table.Column<double>(nullable: true),
                    RecenzRozrobok = table.Column<double>(nullable: true),
                    RecenzRozrobokNStor = table.Column<double>(nullable: true),
                    RobotaNavchGrup = table.Column<double>(nullable: true),
                    Rozrobka15 = table.Column<double>(nullable: true),
                    RozrobkaInterMet = table.Column<double>(nullable: true),
                    RozrobkaInterMetNZanyat = table.Column<double>(nullable: true),
                    RozrobkaLab = table.Column<double>(nullable: true),
                    RozrobkaLabNRobit = table.Column<double>(nullable: true),
                    RozrobkaNavchMat = table.Column<double>(nullable: true),
                    RozrobkaNavchMatNZanyat = table.Column<double>(nullable: true),
                    RozrobkaVNS = table.Column<double>(nullable: true),
                    RozrobkaVNSNDisc = table.Column<double>(nullable: true),
                    RozrobkaZavdan = table.Column<double>(nullable: true),
                    RozrobkaZavdanNZavdan = table.Column<double>(nullable: true),
                    SiteKafedra = table.Column<double>(nullable: true),
                    StagBezVidr = table.Column<double>(nullable: true),
                    StagBezVidrBool = table.Column<bool>(nullable: false),
                    StagZVidr = table.Column<double>(nullable: true),
                    StagZVidrBool = table.Column<bool>(nullable: false),
                    Sum = table.Column<double>(nullable: true),
                    UchastRobGrup = table.Column<double>(nullable: true),
                    UchastRobGrupNDniv = table.Column<double>(nullable: true),
                    User = table.Column<string>(nullable: true),
                    VidannyaPidruch = table.Column<double>(nullable: true),
                    VidannyaRozrobok = table.Column<double>(nullable: true),
                    VzaemVidvid = table.Column<double>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_MetodRobs", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "NaukRobs",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    DopovidKafedra = table.Column<double>(nullable: true),
                    DopovidMijnarod = table.Column<double>(nullable: true),
                    DopovidUkr = table.Column<double>(nullable: true),
                    KerivNaukStud = table.Column<double>(nullable: true),
                    KerivNaukStudMijnarodUkr = table.Column<double>(nullable: true),
                    KerivNaukStudMijnarodZaKordon = table.Column<double>(nullable: true),
                    KerivNaukStudVseukrain = table.Column<double>(nullable: true),
                    KerivStud = table.Column<double>(nullable: true),
                    KerivStudKonkursN = table.Column<double>(nullable: true),
                    KerivStudOhoronDocN = table.Column<double>(nullable: true),
                    KerivStudStattyaN = table.Column<double>(nullable: true),
                    KerivStudTezDopovidN = table.Column<double>(nullable: true),
                    MijnarodDogovir = table.Column<double>(nullable: true),
                    NaukEksped = table.Column<double>(nullable: true),
                    NaukEkspedNDniv = table.Column<double>(nullable: true),
                    OformlennyaKorMod = table.Column<double>(nullable: true),
                    OformlennyaPatent = table.Column<double>(nullable: true),
                    OponDesertDoktor = table.Column<double>(nullable: true),
                    OponDesertDoktorN = table.Column<double>(nullable: true),
                    OponDesertKandidat = table.Column<double>(nullable: true),
                    OponDesertKandidatN = table.Column<double>(nullable: true),
                    OtrymannyaKorMod = table.Column<double>(nullable: true),
                    OtrymannyaPatent = table.Column<double>(nullable: true),
                    PIB = table.Column<string>(nullable: true),
                    PidgotovkaMONGrant = table.Column<double>(nullable: true),
                    PidgotovkaMijnarodGrant = table.Column<double>(nullable: true),
                    PidgotovkaNDR = table.Column<double>(nullable: true),
                    PidgotovkaSpilnProekt = table.Column<double>(nullable: true),
                    PidgotovkaStud = table.Column<double>(nullable: true),
                    PidgotovkaStudMijn = table.Column<double>(nullable: true),
                    PidgotovkaStudMijnUkr = table.Column<double>(nullable: true),
                    PidgotovkaStudMijnZaKordonom = table.Column<double>(nullable: true),
                    RecenzDesertDoktor = table.Column<double>(nullable: true),
                    RecenzDesertDoktorN = table.Column<double>(nullable: true),
                    RecenzDesertKandidat = table.Column<double>(nullable: true),
                    RecenzDesertKandidatN = table.Column<double>(nullable: true),
                    RecenzMonografy = table.Column<double>(nullable: true),
                    RecenzMonografyNStor = table.Column<double>(nullable: true),
                    RecenzStattya = table.Column<double>(nullable: true),
                    RecenzStattyaN = table.Column<double>(nullable: true),
                    StajZakordonVNZ = table.Column<double>(nullable: true),
                    StajZakordonVNZNDniv = table.Column<double>(nullable: true),
                    StattyaMijnarodVitch = table.Column<double>(nullable: true),
                    StattyaMijnarodZakordon = table.Column<double>(nullable: true),
                    StattyaNeMignarod = table.Column<double>(nullable: true),
                    StattyaScopusAngl = table.Column<double>(nullable: true),
                    StattyaScopusUkr = table.Column<double>(nullable: true),
                    Sum = table.Column<double>(nullable: true),
                    User = table.Column<string>(nullable: true),
                    VidannyaFahUkr = table.Column<double>(nullable: true),
                    VidannyaMonografy = table.Column<double>(nullable: true),
                    VidannyaNeFahUkr = table.Column<double>(nullable: true),
                    VistavkaNaukDosMijnarod = table.Column<double>(nullable: true),
                    VistavkaNaukDosRegion = table.Column<double>(nullable: true),
                    VistavkaNaukDosVseukrain = table.Column<double>(nullable: true),
                    ZahistDoktor = table.Column<double>(nullable: true),
                    ZahistDoktorBool = table.Column<bool>(nullable: false),
                    ZahistKandidat = table.Column<double>(nullable: true),
                    ZahistKandidatBool = table.Column<bool>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_NaukRobs", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Navantagennyas",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    Aspiranty = table.Column<double>(nullable: false),
                    Consultant = table.Column<double>(nullable: false),
                    DEK = table.Column<double>(nullable: false),
                    Dyplom = table.Column<double>(nullable: false),
                    Grup = table.Column<int>(nullable: false),
                    Grupa = table.Column<string>(nullable: true),
                    Isput = table.Column<double>(nullable: false),
                    Kontrolny = table.Column<double>(nullable: false),
                    Kurs = table.Column<int>(nullable: false),
                    Kursovi = table.Column<double>(nullable: false),
                    Laborant = table.Column<double>(nullable: false),
                    Lekcii = table.Column<double>(nullable: false),
                    Modul = table.Column<double>(nullable: false),
                    Nazva = table.Column<string>(nullable: true),
                    NumberDisc = table.Column<int>(nullable: false),
                    NumberPP = table.Column<int>(nullable: false),
                    Pidgrup = table.Column<int>(nullable: false),
                    Praktuchni = table.Column<double>(nullable: false),
                    Praktyka = table.Column<double>(nullable: false),
                    Primitka = table.Column<string>(nullable: true),
                    Semestr = table.Column<string>(nullable: true),
                    Studentiv = table.Column<int>(nullable: false),
                    User = table.Column<string>(nullable: true),
                    Vikladach = table.Column<string>(nullable: true),
                    Vsyogo = table.Column<double>(nullable: false),
                    Zalik = table.Column<double>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Navantagennyas", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "NavchRobs",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    DyplomBakalavr = table.Column<double>(nullable: true),
                    DyplomBakalavrNChlen = table.Column<double>(nullable: true),
                    DyplomBakalavrNKeriv = table.Column<double>(nullable: true),
                    DyplomBakalavrNKonsult = table.Column<double>(nullable: true),
                    DyplomMagistr = table.Column<double>(nullable: true),
                    DyplomMagistrNChlen = table.Column<double>(nullable: true),
                    DyplomMagistrNKeriv = table.Column<double>(nullable: true),
                    DyplomMagistrNKonsult = table.Column<double>(nullable: true),
                    DyplomSpecialist = table.Column<double>(nullable: true),
                    DyplomSpecialistNChlen = table.Column<double>(nullable: true),
                    DyplomSpecialistNKeriv = table.Column<double>(nullable: true),
                    DyplomSpecialistNKonsult = table.Column<double>(nullable: true),
                    EkzamenAspirant = table.Column<double>(nullable: true),
                    EkzamenAspirantNStud = table.Column<double>(nullable: true),
                    EkzamenDerjavn = table.Column<double>(nullable: true),
                    EkzamenDerjavnNStud = table.Column<double>(nullable: true),
                    EkzamenInshiPred = table.Column<double>(nullable: true),
                    EkzamenInshiPredNGrup = table.Column<double>(nullable: true),
                    EkzamenInshiPredNRobit = table.Column<double>(nullable: true),
                    EkzamenSluhach = table.Column<double>(nullable: true),
                    EkzamenSluhachNChlen = table.Column<double>(nullable: true),
                    EkzamenTest = table.Column<double>(nullable: true),
                    EkzamenTestNGrup = table.Column<double>(nullable: true),
                    EkzamenUkrMovaDyktant = table.Column<double>(nullable: true),
                    EkzamenUkrMovaDyktantNGrup = table.Column<double>(nullable: true),
                    EkzamenUkrMovaDyktantNRobit = table.Column<double>(nullable: true),
                    EkzamenUkrMovaPerekaz = table.Column<double>(nullable: true),
                    EkzamenUkrMovaPerekazNGrup = table.Column<double>(nullable: true),
                    EkzamenUkrMovaPerekazNRobit = table.Column<double>(nullable: true),
                    EkzamenUkrMovaTvir = table.Column<double>(nullable: true),
                    EkzamenUkrMovaTvirNGrup = table.Column<double>(nullable: true),
                    EkzamenUkrMovaTvirNRobit = table.Column<double>(nullable: true),
                    EkzamenUsn = table.Column<double>(nullable: true),
                    EkzamenUsnNStud = table.Column<double>(nullable: true),
                    Individual = table.Column<double>(nullable: true),
                    KerivnukAspirant = table.Column<double>(nullable: true),
                    KerivnukAspirantN = table.Column<double>(nullable: true),
                    KerivnukSluhach = table.Column<double>(nullable: true),
                    KerivnukSluhachNChlen = table.Column<double>(nullable: true),
                    KerivnukSluhachNKeriv = table.Column<double>(nullable: true),
                    KerivnukSluhachNKonsult = table.Column<double>(nullable: true),
                    KerivnukStajSluhach = table.Column<double>(nullable: true),
                    KerivnukStajSluhachN = table.Column<double>(nullable: true),
                    KerivnukStajVikladach = table.Column<double>(nullable: true),
                    KerivnukZdobuvach = table.Column<double>(nullable: true),
                    KerivnukZdobuvachN = table.Column<double>(nullable: true),
                    KonsultDokrtor = table.Column<double>(nullable: true),
                    KonsultDokrtorN = table.Column<double>(nullable: true),
                    KonsultEkzamDerj = table.Column<double>(nullable: true),
                    KonsultEkzamDerjNGrup = table.Column<double>(nullable: true),
                    KonsultEkzamSemestr = table.Column<double>(nullable: true),
                    KonsultEkzamSemestrNGrup = table.Column<double>(nullable: true),
                    KonsultEkzamVstup = table.Column<double>(nullable: true),
                    KonsultEkzamVstupNGrup = table.Column<double>(nullable: true),
                    KonsultNavch = table.Column<double>(nullable: true),
                    Laboratorni = table.Column<double>(nullable: true),
                    Lekcii = table.Column<double>(nullable: true),
                    PIB = table.Column<string>(nullable: true),
                    PerevirkaGraf = table.Column<double>(nullable: true),
                    PerevirkaGrafN = table.Column<double>(nullable: true),
                    PerevirkaKontr = table.Column<double>(nullable: true),
                    PerevirkaKontrN = table.Column<double>(nullable: true),
                    PerevirkaKursProjFah = table.Column<double>(nullable: true),
                    PerevirkaKursProjFahNrobit = table.Column<double>(nullable: true),
                    PerevirkaKursProjZagIng = table.Column<double>(nullable: true),
                    PerevirkaKursProjZagIngNRobit = table.Column<double>(nullable: true),
                    PerevirkaKursRobFah = table.Column<double>(nullable: true),
                    PerevirkaKursRobFahNRobit = table.Column<double>(nullable: true),
                    PerevirkaKursRobZagOsv = table.Column<double>(nullable: true),
                    PerevirkaKursRobZagOsvNRobit = table.Column<double>(nullable: true),
                    PerevirkaRefer = table.Column<double>(nullable: true),
                    PerevirkaReferN = table.Column<double>(nullable: true),
                    Prakticni = table.Column<double>(nullable: true),
                    PraktikDiplomna = table.Column<double>(nullable: true),
                    PraktikNavchalna = table.Column<double>(nullable: true),
                    PraktikVirobn = table.Column<double>(nullable: true),
                    RecenzReferat = table.Column<double>(nullable: true),
                    RecenzReferatNRobit = table.Column<double>(nullable: true),
                    SemestEkzPism = table.Column<double>(nullable: true),
                    SemestEkzPismNGrup = table.Column<double>(nullable: true),
                    SemestEkzPismNRobit = table.Column<double>(nullable: true),
                    SemestEkzUsn = table.Column<double>(nullable: true),
                    SemestEkzUsnNGrup = table.Column<double>(nullable: true),
                    Seminar = table.Column<double>(nullable: true),
                    Spivbesida = table.Column<double>(nullable: true),
                    SpivbesidaNStud = table.Column<double>(nullable: true),
                    Sum = table.Column<double>(nullable: true),
                    TematDisc = table.Column<double>(nullable: true),
                    User = table.Column<string>(nullable: true),
                    Zalik = table.Column<double>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_NavchRobs", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "NormatKilkistBalivOrgRobs",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    AdminWebMerejKafedra = table.Column<double>(nullable: true),
                    AdminWebMerejKafedraBool = table.Column<bool>(nullable: false),
                    CivilOboron = table.Column<double>(nullable: true),
                    CivilOboronBool = table.Column<bool>(nullable: false),
                    EstetKaredra = table.Column<double>(nullable: true),
                    FormIndividPlanStud = table.Column<double>(nullable: true),
                    FormIndividPlanStudNStud = table.Column<double>(nullable: true),
                    FormKontingentVstupMagistr = table.Column<double>(nullable: true),
                    FormKontingentVstupMagistrNStud = table.Column<double>(nullable: true),
                    KerivSudKlubSekciya = table.Column<double>(nullable: true),
                    KerivSudKlubSekciyaBool = table.Column<bool>(nullable: false),
                    KontrolYakostiPidgFah = table.Column<double>(nullable: true),
                    KontrolYakostiPidgFahIndividZavdNStud = table.Column<double>(nullable: true),
                    KontrolYakostiPidgFahKontrRobNStud = table.Column<double>(nullable: true),
                    KontrolYakostiPidgFahKontrRobZaochNStud = table.Column<double>(nullable: true),
                    KontrolYakostiPidgFahRozrahGrafRobNStud = table.Column<double>(nullable: true),
                    OcinRobVikladach = table.Column<double>(nullable: true),
                    OcinRobVikladachBool = table.Column<bool>(nullable: false),
                    OhoronaPraci = table.Column<double>(nullable: true),
                    OhoronaPraciBool = table.Column<bool>(nullable: false),
                    OrgDistancZahid = table.Column<double>(nullable: true),
                    OrgMijnarodMobil = table.Column<double>(nullable: true),
                    OrgMijnarodMobilNStud = table.Column<double>(nullable: true),
                    OrgMijnarodZahid = table.Column<double>(nullable: true),
                    OrgNaukSemNAN = table.Column<double>(nullable: true),
                    OrgNaukSemNANGolovaBool = table.Column<bool>(nullable: false),
                    OrgNaukSemNANSekretarBool = table.Column<bool>(nullable: false),
                    OrgNavchDiscInozemMova = table.Column<double>(nullable: true),
                    OrgNavchDiscInozemMovaNDisc = table.Column<double>(nullable: true),
                    OrgOlimpDrugEtap = table.Column<double>(nullable: true),
                    OrgOlimpPershEtap = table.Column<double>(nullable: true),
                    OrgPislyaDiplomOsv = table.Column<double>(nullable: true),
                    OrgPislyaDiplomOsvBool = table.Column<bool>(nullable: false),
                    OrgPodvDyplom = table.Column<double>(nullable: true),
                    OrgPodvDyplomNStud = table.Column<double>(nullable: true),
                    OrgTaProvKultZahid = table.Column<double>(nullable: true),
                    OrgTaProvTematVechir = table.Column<double>(nullable: true),
                    OrgTaSuprovidNaukMetRobKafedra = table.Column<double>(nullable: true),
                    OrgTaSuprovidNaukMetRobKafedraBool = table.Column<bool>(nullable: false),
                    OrgUniverStudZahid = table.Column<double>(nullable: true),
                    OrgVseUkrZahid = table.Column<double>(nullable: true),
                    OrgZyazokZVipusk = table.Column<double>(nullable: true),
                    OrgZyazokZVipuskBool = table.Column<bool>(nullable: false),
                    PIB = table.Column<string>(nullable: true),
                    PidOrgTaProvSvorchZahod = table.Column<double>(nullable: true),
                    PidgotDyplomVseUkr = table.Column<double>(nullable: true),
                    PidgotDyplomVseUkrNRobit = table.Column<double>(nullable: true),
                    ProfOrientRob = table.Column<double>(nullable: true),
                    ProfOrientRobNDniv = table.Column<double>(nullable: true),
                    ProvedennyaEkskurs = table.Column<double>(nullable: true),
                    ProvedennyaEkskursNZahid = table.Column<double>(nullable: true),
                    RobotaEkspKonkursKomis = table.Column<double>(nullable: true),
                    RobotaEkspKonkursKomisNNINZasid = table.Column<double>(nullable: true),
                    RobotaEkspKonkursKomisUniverNZasid = table.Column<double>(nullable: true),
                    RobotaEksperKomisDesertDoktor = table.Column<double>(nullable: true),
                    RobotaEksperKomisDesertKandidat = table.Column<double>(nullable: true),
                    RobotaFormNaukVidanMijnarod = table.Column<double>(nullable: true),
                    RobotaFormNaukVidanScopus = table.Column<double>(nullable: true),
                    RobotaFormNaukVidanUkr = table.Column<double>(nullable: true),
                    RobotaIzPracevlashtuvannya = table.Column<double>(nullable: true),
                    RobotaIzPracevlashtuvannyaBool = table.Column<bool>(nullable: false),
                    RobotaKomisPoperedZahistDyplom = table.Column<double>(nullable: true),
                    RobotaKomisPoperedZahistDyplomBool = table.Column<bool>(nullable: false),
                    RobotaMetodRad = table.Column<double>(nullable: true),
                    RobotaMetodRadNZasid = table.Column<double>(nullable: true),
                    RobotaNaukMetodNaukTehRadah = table.Column<double>(nullable: true),
                    RobotaNaukMetodNaukTehRadahNZasid = table.Column<double>(nullable: true),
                    RobotaPrimKomis = table.Column<double>(nullable: true),
                    RobotaPrimKomisOsobamBool = table.Column<bool>(nullable: false),
                    RobotaPrimKomisSekretarBool = table.Column<bool>(nullable: false),
                    RobotaRadaDesert = table.Column<double>(nullable: true),
                    RobotaRadaDesertChlenNZasid = table.Column<double>(nullable: true),
                    RobotaRadaDesertGolovaNZasid = table.Column<double>(nullable: true),
                    RobotaRadaDesertSekretarNZasid = table.Column<double>(nullable: true),
                    RobotaRedakNaukVidan = table.Column<double>(nullable: true),
                    RobotaRedakNaukVidanNVipusk = table.Column<double>(nullable: true),
                    RobotaRozvitokMijnarodZvyazok = table.Column<double>(nullable: true),
                    RobotaRozvitokMijnarodZvyazokKafedraBool = table.Column<bool>(nullable: false),
                    RobotaRozvitokMijnarodZvyazokNNIBool = table.Column<bool>(nullable: false),
                    RobotaVKomisMON = table.Column<double>(nullable: true),
                    RobotaVKomisMONNZasid = table.Column<double>(nullable: true),
                    RobotaVchenaRadaUniver = table.Column<double>(nullable: true),
                    RobotaVchenaRadaUniverClenNZasid = table.Column<double>(nullable: true),
                    RobotaVchenaRadaUniverSekretarNNIBool = table.Column<bool>(nullable: false),
                    RobotaVchenaRadaUniverSekretarUniverBool = table.Column<bool>(nullable: false),
                    RobotaVikladachKurator = table.Column<double>(nullable: true),
                    RobotaVikladachKuratorBool = table.Column<bool>(nullable: false),
                    RozpodilNavchNavant = table.Column<double>(nullable: true),
                    RozpodilNavchNavantBool = table.Column<bool>(nullable: false),
                    RozrobSaitKafedra = table.Column<double>(nullable: true),
                    RozrobkaDodatkivMijnarod = table.Column<double>(nullable: true),
                    RozrobkaDodatkivMijnarodBool = table.Column<bool>(nullable: false),
                    SekretarEK = table.Column<double>(nullable: true),
                    SekretarEKBool = table.Column<bool>(nullable: false),
                    SekretarKafedra = table.Column<double>(nullable: true),
                    SekretarKafedraBool = table.Column<bool>(nullable: false),
                    StajVikladach = table.Column<double>(nullable: true),
                    Sum = table.Column<double>(nullable: true),
                    SuprovidVirtNavchSered = table.Column<double>(nullable: true),
                    SuprovidVirtNavchSeredBool = table.Column<bool>(nullable: false),
                    SuprovidWebStorKafedra = table.Column<double>(nullable: true),
                    UchastRadHimRozvidka = table.Column<double>(nullable: true),
                    UchastRadHimRozvidkaBool = table.Column<bool>(nullable: false),
                    UchastTovarMolodVchen = table.Column<double>(nullable: true),
                    UchastTovarMolodVchenBool = table.Column<bool>(nullable: false),
                    UchastURozrobSystemUniver = table.Column<double>(nullable: true),
                    UchastURozrobSystemUniverBool = table.Column<bool>(nullable: false),
                    User = table.Column<string>(nullable: true),
                    VprovSystemVipuskPrac = table.Column<double>(nullable: true),
                    VprovSystemVipuskPracBool = table.Column<bool>(nullable: false),
                    ZvyazokBiblioteka = table.Column<double>(nullable: true),
                    ZvyazokBibliotekaBool = table.Column<bool>(nullable: false),
                    ZvyazokPidprPrakt = table.Column<double>(nullable: true),
                    ZvyazokPidprPraktBool = table.Column<bool>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_NormatKilkistBalivOrgRobs", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "OrgRobs",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    EstetKaredra = table.Column<double>(nullable: true),
                    EstetKaredraBool = table.Column<bool>(nullable: false),
                    KerivnukKafedra = table.Column<double>(nullable: true),
                    KerivnukKafedraBool = table.Column<bool>(nullable: false),
                    ObovjazokKafedra = table.Column<double>(nullable: true),
                    ObovjazokKafedraSekretarBool = table.Column<bool>(nullable: false),
                    ObovjazokKafedraZastupnikBool = table.Column<bool>(nullable: false),
                    OrgKafedraZahid = table.Column<double>(nullable: true),
                    OrgKafedraZahidBool = table.Column<bool>(nullable: false),
                    OrgZagalUniverZahid = table.Column<double>(nullable: true),
                    OrgZagalUniverZahidBool = table.Column<bool>(nullable: false),
                    OrganizaciaEkskurs = table.Column<double>(nullable: true),
                    OrganizaciaEkskursBool = table.Column<bool>(nullable: false),
                    PIB = table.Column<string>(nullable: true),
                    PidtrumkaWEB = table.Column<double>(nullable: true),
                    PidtrumkaWEBBool = table.Column<bool>(nullable: false),
                    ProvedennyaBesid = table.Column<double>(nullable: true),
                    ProvedennyaBesidBool = table.Column<bool>(nullable: false),
                    RobotaRevizia = table.Column<double>(nullable: true),
                    RobotaReviziaGolovaBool = table.Column<bool>(nullable: false),
                    RobotaReviziaSekretarBool = table.Column<bool>(nullable: false),
                    RobotaReviziaZastupnikBool = table.Column<bool>(nullable: false),
                    RobotaTrudKolektiv = table.Column<double>(nullable: true),
                    RobotaTrudKolektivClenBool = table.Column<bool>(nullable: false),
                    RobotaTrudKolektivGolovaBool = table.Column<bool>(nullable: false),
                    RobotaTrudKolektivSekretarBool = table.Column<bool>(nullable: false),
                    RobotaTrudKolektivZastupnikBool = table.Column<bool>(nullable: false),
                    RobotaVchenaRada = table.Column<double>(nullable: true),
                    RobotaVchenaRadaClenBool = table.Column<bool>(nullable: false),
                    RobotaVchenaRadaGolovaBool = table.Column<bool>(nullable: false),
                    RobotaVchenaRadaSekretarBool = table.Column<bool>(nullable: false),
                    RozrobkaMaterialivZahid = table.Column<double>(nullable: true),
                    RozrobkaMaterialivZahidPhotoBool = table.Column<bool>(nullable: false),
                    RozrobkaMaterialivZahidPrezentaciaBool = table.Column<bool>(nullable: false),
                    RozrobkaMaterialivZahidVideoBool = table.Column<bool>(nullable: false),
                    SekretarNaukMetodSeminar = table.Column<double>(nullable: true),
                    SekretarNaukMetodSeminarNZasid = table.Column<double>(nullable: true),
                    SekretarPrijomKomis = table.Column<double>(nullable: true),
                    SekretarPrijomKomisBool = table.Column<bool>(nullable: false),
                    Sum = table.Column<double>(nullable: true),
                    UchastProfOrient = table.Column<double>(nullable: true),
                    UchastProfOrientBool = table.Column<bool>(nullable: false),
                    User = table.Column<string>(nullable: true),
                    ZasidannyaKafedra = table.Column<double>(nullable: true),
                    ZasidannyaKafedraNZasid = table.Column<double>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_OrgRobs", x => x.Id);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "MetodRobs");

            migrationBuilder.DropTable(
                name: "NaukRobs");

            migrationBuilder.DropTable(
                name: "Navantagennyas");

            migrationBuilder.DropTable(
                name: "NavchRobs");

            migrationBuilder.DropTable(
                name: "NormatKilkistBalivOrgRobs");

            migrationBuilder.DropTable(
                name: "OrgRobs");
        }
    }
}
